### ISSUE TITLE
RSS feed sends out relative URL

### ISSUE THREAD

**Issue by fbarbe00** [xplosionmind/tommi.space#107]
From the latest RSS feed post:
```json
{
  "id": "https://tommi.space/palestinian-dinner/",
  "url": "/palestinian-dinner/",
  "urls": [
    "/palestinian-dinner/"
  ],
  "links": [
    {
      "href": "/palestinian-dinner/"
    }
  ],
  "title": "Palestinian dinner",
  "description": null,
  "content": "<p>https://pan.rent/@tommi/111727638920947709<\/p>\n<p>https://pan.rent/@tommi/111728443280171255<\/p>\n",
  "image": null,
  "enclosure": null,
  "authors": [

  ],
  "categories": [

  ],
  "date_published": null,
  "last_updated": "2024-01-20T19:00:00+00:00"
}
```

The "url" should ideally be `https://tommi.space/palestinian-dinner/`, `/palestinian-dinner/`

**Comment by xplosionmind** [comment]
Thanks a lot for reporting this bug, @fbarbe00!  
I am both glad and honored that you are so meticulously fetching the RSS feeds generated by tommi.space.

I will address this issue immediately.

**Comment by xplosionmind** [comment]
Mmmmh, tackling this is making me spot a lot of problems with all the XML and JSON feeds… I must work on #65 too, then.

**Comment by fbarbe00** [comment]
Hi, where did the feed move? https://tommi.space/all.xml no longer works

**Comment by fbarbe00** [comment]
In fact, https://tommi.space/feeds/ doesn't work too, despite still being indexed by some search engines

**Comment by xplosionmind** [comment]
Damn, I made a breaking change during the feeds refactoring, and I did not properly transition.

For the moment, the main RSS feed is available at https://tommi.space/index.xml
